(() => {
  'use strict';
  const e = v => String(v ?? '—').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const tags = list => list.map(t => `<span class="issue-tag">${e(t)}</span>`).join(' ');
  const link = f => /^https:\/\//.test(f.url || '') ? `<a href="${e(f.url)}" target="_blank" rel="noopener noreferrer">${e(f.source)} · ${e(f.summary)}</a>` : e(f.source);
  const status = document.getElementById('issuestatus');
  fetch('issue-spread.json', {cache:'no-store'}).then(r => {if (!r.ok) throw Error('load');return r.json();}).then(d => {
    const today = new Intl.DateTimeFormat('sv-SE', {timeZone:'Asia/Seoul'}).format(new Date());
    status.textContent = `${d.status} · 기준 ${d.generatedAt || '미수집'} · ${d.slot || '실행 대기'}${d.sourceDate && d.sourceDate < today ? ' · 이전 거래일 자료' : ''}`;
    document.getElementById('issuebody').innerHTML = `<p class="issue-note">08:00 탐색 → 10:30 시장 확인 → 15:00 최종 검증 · KRX 영업일만 실행<br>이슈 20 + 주도주 20 + 확산 20 + 펀더멘털 30 + 진입위치 10점. 유튜브는 탐지용이며 점수에 반영하지 않습니다.</p>${(d.missing || []).map(x=>`<p>${e(x)}</p>`).join('')}${(d.issues || []).map(i => `<details class="issue-card" open><summary><strong>${e(i.name)}</strong><span>이슈강도 ${e(i.strength)} · 시장확산 ${e(i.marketGrade)} · 펀더멘털 ${e(i.fundamentalGrade)}</span></summary><p>${e(i.spreadType)}</p><h3>해외 선행주 · 국내 주도주</h3><div class="issue-leaders">${i.leaders.map(l=>`<article><strong>${e(l.name)}</strong> · ${e(l.market)}<p>${tags(l.tags)}</p><small>등락 ${e(l.quote.changePct)}% · 5일 ${e(l.quote.return5dPct)}% · 거래대금 ${e(l.quote.turnoverRatio)}배<br>가격 기준 ${e(l.quote.asOf)}</small></article>`).join('') || '주도주 검증 대기'}</div><h3>직접 수혜 · 확산 후보</h3><div class="issue-tablewrap"><table class="issue-table"><thead><tr>${['종목','직접수혜도','실적연결도','순환강도','주가확인','과열도','종합점수','현재 단계'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${i.candidates.map(r=>`<tr><td><strong>${e(r.name)}</strong><small>${e(r.sector)}</small>${tags(r.tags)}<small>${e(r.matchedBoards.join(' + '))}</small></td><td>${r.direct ? '직접수혜 확인' : '검증대기'}</td><td>${e(r.fundamental)}/30<small>${e(r.earningsPeriods.join(' · '))}</small></td><td>${e(r.scores.spread)}/20</td><td>${e(r.priceStatus)}<small>${e(r.quote.asOf)}</small></td><td>${e(r.overheat)}<small>진입 ${e(r.scores.entry)}/10</small></td><td><strong>${e(r.score)}/100</strong></td><td>${e(r.stage)}</td></tr>`).join('') || '<tr><td colspan="8">직접 수혜 연결 근거를 검토하고 있습니다.</td></tr>'}</tbody></table></div><details><summary>검증 근거 · 원문과 확인 시각</summary>${i.evidence.map(f=>`<p>${link(f)}<br><small>공개 ${e(f.publishedAt)} · 검증 ${e(f.verifiedAt)}</small></p>`).join('') || '<p>신뢰 가능한 원문 검증 대기 · 추천 가산 없음</p>'}</details></details>`).join('') || '<div class="issue-card">아직 확인된 이슈가 없습니다. 검증된 원자료가 확보되면 최대 3개 이슈와 후보를 표시합니다.</div>'}`;
  }).catch(() => {status.textContent='이슈 확산 자료 불러오기 실패 · 다른 평가창은 계속 표시됩니다.';});
})();
